[workspace]
resolver = "2"

members = ["desktop", "parser"]

[workspace.package]
edition      = "2021"
rust-version = "1.75.0"

[workspace.dependencies]
color-eyre = "0.6.3"
serde      = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.128"
